/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StateCodeRouteImport } from './routes/state.$code'
import { Route as HooksIngestNewsRouteImport } from './routes/hooks/ingest-news'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateCodeRoute = StateCodeRouteImport.update({
  id: '/state/$code',
  path: '/state/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIngestNewsRoute = HooksIngestNewsRouteImport.update({
  id: '/hooks/ingest-news',
  path: '/hooks/ingest-news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hooks/ingest-news': typeof HooksIngestNewsRoute
  '/state/$code': typeof StateCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hooks/ingest-news': typeof HooksIngestNewsRoute
  '/state/$code': typeof StateCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hooks/ingest-news': typeof HooksIngestNewsRoute
  '/state/$code': typeof StateCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hooks/ingest-news' | '/state/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hooks/ingest-news' | '/state/$code'
  id: '__root__' | '/' | '/hooks/ingest-news' | '/state/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HooksIngestNewsRoute: typeof HooksIngestNewsRoute
  StateCodeRoute: typeof StateCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/$code': {
      id: '/state/$code'
      path: '/state/$code'
      fullPath: '/state/$code'
      preLoaderRoute: typeof StateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/ingest-news': {
      id: '/hooks/ingest-news'
      path: '/hooks/ingest-news'
      fullPath: '/hooks/ingest-news'
      preLoaderRoute: typeof HooksIngestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HooksIngestNewsRoute: HooksIngestNewsRoute,
  StateCodeRoute: StateCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
